<?php
/**
 * User: Alex Gusev <alex@flancer64.com>
 */

namespace Praxigento\Warehouse\Ui\DataProvider;


class Warehouse extends \Magento\Ui\DataProvider\AbstractDataProvider
{

    protected $_fieldsToSelect = [];

    public function __construct(
        $name = 'DataSourceDefault',
        $primaryFieldName = 'entity_id',
        $requestFieldName = 'id',
        array $meta = [],
        array $data = []
    ) {
        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data);
    }

    public function addField($field, $alias = null)
    {
        // parent::addField($field, $alias);
        $this->_fieldsToSelect[] = $field;
    }

    public function getData()
    {
        // return parent::getData(); // TODO: Change the autogenerated stub
        $result = [['id' => 10], ['id' => 20]];
        $result = [];
        return $result;
    }

    public function setConfigData($config)
    {
        parent::setConfigData($config);
    }

}